# Generated by Django 4.1.13 on 2024-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kayphone',
            field=models.CharField(default='+967', max_length=8),
        ),
    ]
