# Generated by Django 4.1.13 on 2024-07-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(0, 'Out of stock'), (1, 'Low stock'), (2, 'In stock')]),
        ),
    ]
