# Generated by Django 4.1.13 on 2024-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('out_of_stock', 'Out of stock'), ('low_stock', 'Low stock'), ('in_stock', 'In stock')], default='in_stock', max_length=20),
        ),
    ]
