# Generated by Django 4.1.13 on 2024-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceOld',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
