# Generated by Django 4.1.13 on 2024-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_priceold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='30-20', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Post office', max_length=100),
        ),
    ]
